{
 "title": "Pizza Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_total{source=\"jwt-pizza-service\", category=\"get\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(http_total{category=\"get\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(http_total{category=\"post\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(http_total{category=\"delete\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(http_total{category=\"put\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_latency{category=\"request\", source=\"jwt-pizza-service\"}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "business_sold{source=\"jwt-pizza-service\", category=\"pizzas\"}",
     "legendFormat": "success"
    },
    {
     "expr": "business_purchase_failures{category=\"pizzas\", source=\"jwt-pizza-service\"}",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "business_total{category=\"revenue\", source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "business_latency{category=\"order\", source=\"jwt-pizza-service\"}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(auth_success{category=\"attempts\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_failed{category=\"attempts\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{category=\"memory\", source=\"jwt-pizza-service\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "system_usage{category=\"cpu\", source=\"jwt-pizza-service\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "users_count{category=\"active\", source=\"jwt-pizza-service\"}",
     "legendFormat": "active"
    }
   ]
  }
 ]
}